### ISSUE TITLE
Add support for AppImage distribution

### ISSUE THREAD

**Issue by Poohblah** [sous-chefs/vagrant#111]
## :person_frowning: Problem Statement

The AppImage-based distribution of Vagrant (i.e. the generic Linux download available on the [official downloads page](https://www.vagrantup.com/downloads.html)) is more reliable and robust than the .rpm/.deb/etc. distribution, since it's an OS-agnostic, self-contained distribution bundled with all its dependencies and won't conflict with the OS's Ruby/gems/etc.  However, this cookbook doesn't support installing the AppImage distribution.

## :grey_question: Possible Solution

Add support to this cookbook for installing the AppImage distribution on any Linux OS.

## :arrow_heading_up: Describe alternatives you've considered

Not using this cookbook.

## :heavy_plus_sign: Additional context

Think that's about it for this feature request :)

**Comment by MarkGibbons** [comment]
Where is the applemage distribution located?

**Comment by Poohblah** [comment]
The AppImage distribution is the generic "Linux" download on the official Vagrant downloads page:

https://www.vagrantup.com/downloads.html

It's just a zip file containing a single executable.

**Comment by MarkGibbons** [comment]
@Poohblah I looked and didn't find any documentation explaining that executable.  Do you know of some?  What OS images should we expect that to run on?
Thanks

**Comment by Poohblah** [comment]
Here's the information I do have:

From the  [blog post where the AppImage package was announced](https://www.hashicorp.com/blog/hashicorp-vagrant-2-1-0):

> The Vagrant 2.1.0 release includes the initial offering of a generic Linux package for Vagrant. This package includes a single Vagrant executable file which users can install into a directory on their PATH. The Vagrant executable in this package is an AppImage application and is intended for distributions where a native Vagrant package may not available.

I would add that I have also found the AppImage package very useful even for OSes that have a native Vagrant package, since the native package tends to rely on the system Ruby and Gems and this has led to issues with Vagrant having conflicting Ruby and/or Gem requirements with other packages on the system.

As for what OSes it should run on, the executable itself is a 64-bit ELF executable with no link-time dependencies and a run-time dependency on FUSE, so in theory it should run on any 64-bit Linux-based OS with FUSE installed.  The [AppImage documentation](https://docs.appimage.org/introduction/index.html) says that OS compatibility depends on how the packager made the package, but I can't find any official statements from Hashicorp about precisely what OSes the package is intended to be compatible with.

**Comment by MarkGibbons** [comment]
Thanks for the link.

**Comment by MarkGibbons** [comment]
PR #120

**Comment by MarkGibbons** [comment]
Merged, I'll publish on supermarket soon.
