### ISSUE TITLE
Remote or adjust for user dependency

### ISSUE THREAD

**Issue by PowerSchill** [sous-chefs/vagrant#124]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The tests for the cookbook have a user component. It assumed that the "default" user was `vagrant` however on the dokken images the default user is `root`. In order to get docker builds to succeed the user in the tests had to switched to `root`. 

## :pancakes: Cookbook version

Master Branch

## :woman_cook:  Chef-Infra Version

N/A

## :tophat: Platform details

N/A

## Steps To Reproduce

N/A

## :police_car: Expected behavior

The tests should either create any users that need to be created or not dependent on whatever the default user that runs the cookbook  is.

## :heavy_plus_sign: Additional context

N/A

**Comment by MarkGibbons** [comment]
We need to keep the tests with the non root user.

**Comment by PowerSchill** [comment]
Then we need to create a user to use. The problem with the docker builds is that it doesn't use the vagrant user so the tests will always fail in CircleCI

**Comment by MarkGibbons** [comment]
Fixed by #145
