### ISSUE TITLE
Can't install plugins from behind proxy

### ISSUE THREAD

**Issue by jblaine** [sous-chefs/vagrant#64]
Unless I'm mistaken, https://github.com/jtimberman/vagrant-cookbook/blob/master/libraries/plugin.rb#L77 appears to override all of ENV when it installs plugins via CLI and that trashes our ENV['https_proxy'] environment variable.

**Comment by MarkGibbons** [comment]
Hi jblaine,

I substituted an env command for the other commands at line 77.  The output shows the proxy values I had set before calling the shell_out! method.  I don't think vagrant is wiping out the env settings.  If you still have this problem please reopen the issue.

thanks,
   Mark
