### ISSUE TITLE
Fetching checksums at compile time breaks the cookbook in complicated environments

### ISSUE THREAD

**Issue by jjustice6** [sous-chefs/vagrant#69]
We have a situation in which we have a cookbook that sets up SSL certificates as well as installing common dev software, including Vagrant.

We use `remote_directory` to put certs in a folder, notifying a block that runs either `update-ca-certificates` (if Ubuntu) or `update-ca-trust` (if RHEL). This is pretty straightforward stuff.

The problem is that happens at runtime, and if I want to also install Vagrant, the cookbook fails *at compile time* because, without the SSL certificates, it can't go get the checksums here: https://github.com/jtimberman/vagrant-cookbook/blob/master/libraries/helpers.rb#L60-L63

**Comment by cheeseplus** [comment]
I think this could be fairly easily mitigated and probably will tackle it moving to custom resources.

**Comment by MarkGibbons** [comment]
http://notetoself.vrensk.com/2008/09/verified-https-in-ruby/  is probably relevant for a solution. Using the chef supplied cacerts.pem file will pull in the usual suspects for CA authorities.

**Comment by MarkGibbons** [comment]
Should be fixed by #91.  Up for review.

**Comment by MarkGibbons** [comment]
#91 was merged.

**Comment by jjustice6** [comment]
Awesome, this is great news.
