### ISSUE TITLE
Trying to install vagrant plugins fails during testing.

### ISSUE THREAD

**Issue by MarkGibbons** [sous-chefs/vagrant#82]
Found during release testing.
The vagrant_plugin resource tests to see if the plugin is already installed.  The vagrant plugin list command returns a nonzero status and installing the plugin fails. 
           ================================================================================
           Error executing action `install` on resource 'vagrant_plugin[vagrant-ohai]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '-1073741515'
           ---- Begin output of vagrant plugin list ----
           STDOUT:
           STDERR:
           ---- End output of vagrant plugin list ----
           Ran vagrant plugin list returned -1073741515

**Comment by rjhornsby** [comment]
I've been digging into this cookbook to try to resolve some of the challenges around Windows. #82 seems to be related to the version of Vagrant. `1.9.7` behaves badly, but `2.0.3` is able to install plugins okay.

There are some other things a bit wonky w/r/t Windows (so _just_ changing the version isn't enough in total), but the Vagrant version definitely is related to this `-1073741515` error.

Working to verify that my cookbook changes don't break Linux support before I toss you a PR.

**Comment by MarkGibbons** [comment]
I'm immensely grateful. Thank you

**Comment by MarkGibbons** [comment]
This issue was resolved by rjhornsby's PR.
