### ISSUE TITLE
Chef 13 requirement should be a major change not minor

### ISSUE THREAD

**Issue by bkonick** [sous-chefs/vagrant#94]
### Cookbook version
0.9.1

### Chef-client version
ChefDK 1.6.11

### Platform Details
RHEL 7.x

### Scenario:
Cookbook bombs out because the version requirement was changed to `>= 13`. We are almost moved off of the EOL version, but I had a cookbook still testing on ChefDK 1.x and noticed this with the latest build.

### Steps to Reproduce:
Use Chef `<= 12`

### Expected Result:
Expected result is more of a philosophical one. I would expect a new minimum Chef client version to be a major breaking change rather than minor. Maybe that's up for debate since this is still major version 0 ?

### Actual Result:
Cookbook bombs out because the version requirement was changed to `>= 13`

**Comment by cheeseplus** [comment]
In general the advice here would be to pin to an older version, with Chef 12 being EOL it's hard to justify keeping support for it.

**Comment by bkonick** [comment]
@cheeseplus I agree 100%. Being on Chef 12 still is the bane of my existence 😅 haha. I was just curious about why this wasn't a major change? Is it solely because 12 is EOL or just an oversight?

**Comment by cheeseplus** [comment]
Cookbooks don't always increment major for the underlying software - I can totally see the argument for it being a breaking change but given that we're only 6 months out from starting to deprecate 13 it was probably just bringing up to speed (potentially an oversight) - lots of cookbooks had never had the chef_version set/maintained properly.

**Comment by bkonick** [comment]
Alrighty no problem. I'll go ahead and close this. Thanks for following up! 😎
